---
title: "knitr Options"
author: "Cassandra"
date: "August 19, 2019"
output: 
  html_document: 
    keep_md: yes
---

## Help! My file takes forever to knit :(

Do you get annoyed when you need to knit a file that has many graphs because it takes forever? You can set up your file with this code chunk at the top to help fix that problem. Just remove the `#` so that R recognizes it properly. 

```{#r include = FALSE}  
knitr::opts_chunk$set(cache = TRUE, autodep = TRUE)
```

`include = FALSE` makes it so that this chunk will not show up in your final document. The `knitr` line that it runs sets the options so that R will store your graphs every time you knit this file. Then if you knit it again later it will only re-knit code that has been changed or added. Overall, this won't help you if you only knit your file once, but it will help if you knit the same file multiple times as you work on it. 

## I don't want to see all the package messages in my final file, what do I do?

Again, remove the `#` so that R can recognize this code chunk. You can give all of your code chunks names, which may help when you are troubleshooting a particular piece of code. Here, this code chunk is named `setup` and if R has an error it will reference `setup` instead of saying `code chunk X`. The `message = FALSE` parameter just tells R that we don't want to see any of the messages generated by this code chunk. This is useful when you're loading packages, because people looking at the final document will see which packages you loaded but your document won't be bogged down with extra information about package conflicts and so on. 

```{#r setup, message=FALSE}  
library(tidyverse)
```

When the above code chunk is rendered, it will look like this: 
```{r setup, message=FALSE}  
library(tidyverse)
```